permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

name: Build HTML of site

on: [push, pull_request]

env:
  BRANCH_TO_DEPLOY: "master"
  PYTHON_TO_DEPLOY: "3.6"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        make install

    - name: Build html of site
      run: make publish

    - name: Attach build html
      uses: actions/upload-artifact@v1
      if: matrix.python-version == env.PYTHON_TO_DEPLOY
      with:
        name: html_output
        path: output

    - name: Build tar for github pages
      if: github.ref_name == env.BRANCH_TO_DEPLOY && matrix.python-version == env.PYTHON_TO_DEPLOY
      run: tar --dereference --hard-dereference --directory output/ -cvf artifact.tar .

    - name: Upload tar for github pages
      if: github.ref_name == env.BRANCH_TO_DEPLOY && matrix.python-version == env.PYTHON_TO_DEPLOY
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        if: github.ref_name == env.BRANCH_TO_DEPLOY
        id: deployment
        uses: actions/deploy-pages@v1
